<?php

namespace Portal\PaginawebBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends EntityRepository
{
    
    public function findAll(){
    	
    	$em = $this->getEntityManager();
    	$qb = $em->createQueryBuilder();
    	$qb ->select('p, c');
    	$qb ->from('PortalPaginawebBundle:Producto','p');
    	$qb->leftJoin('p.categoria_codigo', 'c');
    	$qb->leftJoin('c.menu_codigo', 'm');
    	
    	$qb ->orderBy('m.menu_codigo, c.categoria_nombre, p.producto_peso, p.producto_nombre');
    	
    	$query = $qb->getQuery();
    	
    	$productos = $query->getResult();
    	
    	return $productos;
    }
    
    
    public function findMenu($Tipomenu){
    	 
    	$em = $this->getEntityManager();
    	$qb = $em->createQueryBuilder();
    	$qb ->select('p, c');
    	$qb ->from('PortalPaginawebBundle:Producto','p');
    	$qb->leftJoin('p.categoria_codigo', 'c');
    	$qb->leftJoin('c.menu_codigo', 'm');
    	 
    	if($Tipomenu > 0){
    		$qb->where('m.menu_codigo = '.$Tipomenu);
    	}
    	 
    	$qb ->orderBy('m.menu_codigo, c.categoria_codigo, p.producto_peso, p.producto_nombre');
    
    	$query = $qb->getQuery();
    	 
    	$productos = $query->getResult();
    	 
    	return $productos;
    }
}