Portal\PaginawebBundle\Entity\Menu:
  type: entity
  table: menu
  fields:
    menu_codigo:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: menu_codigo
      generator:
        strategy: SEQUENCE
      sequenceGenerator: 
        sequenceName: sq_menu_codigo
        allocationSize: 1
        initialValue: 1
  
    menu_nombre:
      type: string
      length: 255
      unique: false
      fixed: false
      nullable: false
      column: menu_nombre
      
  lifecycleCallbacks: {  }