<?php

namespace Admin\UsuariosBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
	public function findAllPaginated(array $options = NULL)
    {	
		if((isset($options['paginable']) && $options['paginable']) && isset($options['page']) && isset($options['size']))
		{  
			$Iniregister = ($options['page']-1)*$options['size'];
			if ($Iniregister<0) $Iniregister=0;
		} 
		
		$em = $this->getEntityManager();
    	$qb = $em->createQueryBuilder();
		$qb ->select('u.usuario_codigo, u.usuario_nombre, u.usuario_login, u.usuario_email, u.usuario_fechacreacion');
		$qb ->from('AdminUsuariosBundle:Usuario','u');
		
		if((isset($options['order']) && $options['order'])) 
			$qb ->add('orderBy', "u.{$options['order']}");
		else 
			$qb ->orderBy('u.usuario_codigo');
		
		$query = $qb->getQuery();
		if((isset($options['paginable']) && $options['paginable'])){  
			$query ->setFirstResult($Iniregister);
			$query ->setMaxResults($options['size']);
		}
		
		$usuarios = $query->getArrayResult();			
        return $usuarios;
    }
    
    public function findCountAll()
    {
    	$em = $this->getEntityManager();
		$query = $em->createQueryBuilder()
		       	->select('count(u.usuario_codigo)')
        		->from('AdminUsuariosBundle:Usuario','u')
           		->getQuery();
		$count = $query ->getSingleScalarResult();
		return $count;
    }
}