<?php

namespace Admin\UsuariosBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * UsuarioClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioClienteRepository extends EntityRepository
{
	public function findAllClientes(array $options = NULL)
    {	
		$em = $this->getEntityManager();
    	$qb = $em->createQueryBuilder();
		$qb ->select('u.usuario_codigo, u.usuario_nombre, uc.cliente_codigo');
		$qb ->from('AdminUsuariosBundle:UsuarioCliente','uc');
		$qb ->leftJoin('uc.usuario_codigo', 'u');
		 
		if((isset($options['usuario_codigo']))){
			if(trim($options['usuario_codigo'])=='') $options['usuario_codigo'] = 0; 	
			$qb ->where('uc.usuario_codigo = :usuario');
			$qb ->setParameter('usuario', $options['usuario_codigo']);	
		} 		
		$qb ->orderBy('uc.cliente_codigo');
				
		$query = $qb->getQuery();
		$arClientes = $query->getArrayResult();		        
        return $arClientes;  
	}
}