parameters:
    database_driver:   pdo_pgsql
    database_host:     localhost
    database_port:     5432
    database_name:     sfd_2012
    database_user:     sfd_2012
    database_password: sfd_2012

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            es
    secret:            ThisTokenIsNotSoSecretChangeIt
