PortalPaginawebBundle_admin:
    pattern:  /admin   
    defaults: { _controller: PortalPaginawebBundle:Admin:admin }
    options:
        expose: true
        
PortalPaginawebBundle_admininicio:
    pattern:  /admin/inicio   
    defaults: { _controller: PortalPaginawebBundle:Admin:admininicio }
    options:
        expose: true
        
PortalPaginawebBundle_formContacto:
    pattern:  /admin/formContacto
    defaults: { _controller: PortalPaginawebBundle:Admin:formContacto }
    options:
        expose: true

PortalPaginawebBundle_formCategoria:
    pattern:  /admin/formCategoria/{categoria_codigo}
    defaults: { _controller: PortalPaginawebBundle:Admin:formCategoria }
    options:
        expose: true
        
PortalPaginawebBundle_formProducto:
    pattern:  /admin/formProducto/{producto_codigo}
    defaults: { _controller: PortalPaginawebBundle:Admin:formProducto }
    options:
        expose: true
        
PortalPaginawebBundle_addImagen:
    pattern:  /admin/addImagen
    defaults: { _controller: PortalPaginawebBundle:Admin:addImagen }
    options:
        expose: true

PortalPaginawebBundle_formImagen:
    pattern:  /admin/formImagen
    defaults: { _controller: PortalPaginawebBundle:Admin:formImagen }
    options:
        expose: true

PortalPaginawebBundle_cargandocategorias:
    pattern:  /admin/cargandocategorias/{menu_codigo}
    defaults: { _controller: PortalPaginawebBundle:Admin:cargandocategorias }
    options:
        expose: true
        
PortalPaginawebBundle_cargandonuevacategoria:
    pattern:  /admin/cargandonuevacategoria/{categoria_codigo}
    defaults: { _controller: PortalPaginawebBundle:Admin:cargandonuevacategoria }
    options:
        expose: true

PortalPaginawebBundle_eliminandocategoria:
    pattern:  /admin/eliminandocategoria/{categoria_codigo}
    defaults: { _controller: PortalPaginawebBundle:Admin:eliminandocategoria }
    options:
        expose: true
        
PortalPaginawebBundle_eliminarImagenProducto:
    pattern:  /admin/eliminaImagenProducto/{imagen_codigo}
    defaults: { _controller: PortalPaginawebBundle:Admin:eliminaImagenProducto }
    options:
        expose: true

PortalPaginawebBundle_cargandoproductos:
    pattern:  /admin/cargandoproductos/{categoria_codigo}
    defaults: { _controller: PortalPaginawebBundle:Admin:cargandoproductos }
    options:
        expose: true
        
PortalPaginawebBundle_cargandonuevoproducto:
    pattern:  /admin/cargandonuevoproducto/{producto_codigo}
    defaults: { _controller: PortalPaginawebBundle:Admin:cargandonuevoproducto }
    options:
        expose: true
        
PortalPaginawebBundle_addIntroimagen:
    pattern:  /admin/addIntroimagen/{seccion}/{tipo}/{nombrecampo}
    defaults: { _controller: PortalPaginawebBundle:Admin:addIntroimagen }
    options:
        expose: true

PortalPaginawebBundle_cargandointro:
    pattern:  /admin/cargandointro/{menu_codigo}
    defaults: { _controller: PortalPaginawebBundle:Admin:cargandointro }
    prefix: /{_locale}
    options:
        expose: true
    requirements:
        _locale: es|en
        
PortalPaginawebBundle_cargandohojavida:
    pattern:  /admin/cargandohojavida
    defaults: { _controller: PortalPaginawebBundle:Admin:cargandohojavida }
    options:
        expose: true
        
PortalPaginawebBundle_addHojavida:
    pattern:  /admin/addHojavida
    defaults: { _controller: PortalPaginawebBundle:Admin:addHojavida }
    options:
        expose: true
        
PortalPaginawebBundle_cambiarContrasena:
    pattern:  /admin/cambiarContrasena
    defaults: { _controller: PortalPaginawebBundle:Admin:cambiarContrasena }
    options:
        expose: true
        
PortalPaginawebBundle_toxtyComponents:
    pattern:  /admin/toxtyComponents
    defaults: { _controller: PortalPaginawebBundle:Admin:toxtyComponents }
    options:
        expose: true
