parameters:
#    portal_paginaweb.example.class: Portal\PaginawebBundle\Example
    
services:
#    portal_portal.example:
#        class: %portal_portal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

   

